
--CREATING TABLE NETFLIX
DROP TABLE IF EXISTS netflix;
CREATE TABLE NETFLIX (
	SHOW_ID VARCHAR(20),
	TYPE VARCHAR(10),
	TITLE VARCHAR(500),
	DIRECTOR VARCHAR(500),
	CASTS VARCHAR(1000),
	COUNTRY VARCHAR(500),
	DATE_ADDED VARCHAR(50),
	RELEASE_YEAR INT,
	RATING VARCHAR(10),
	DURATION VARCHAR(15),
	LISTED_IN VARCHAR(500),
	DESCRIPTION VARCHAR(300)
);


--SHOWING TABLECOLUMS
SELECT * FROM netflix ;

--COUNT OF DATASET
SELECT 
	COUNT(*) AS TOTAL 
FROM netflix;

-- DISTINCT MOVIE TYPES
SELECT 
	DISTINCT type 
FROM netflix;


-- 15 BUISNESS PROBLEMS 

-- 1. COUNT THE NUMBER OF MOVIES VS TV SHOWS
SELECT
	TYPE,
	COUNT(*) AS TOTAL_COUNT
FROM
	NETFLIX
GROUP BY
	TYPE;



-- 2. FIND THE MOST COMMOM RATING FOR THE MOVIES AND TV SHOWS 

SELECT
	TYPE,
	RATING,
	TOTAL,
	RANKING
FROM
	(
		SELECT
			TYPE,
			RATING,
			COUNT(*) AS TOTAL,
			RANK() OVER (
				PARTITION BY
					TYPE
				ORDER BY
					COUNT(*) DESC
			) AS RANKING
		FROM
			NETFLIX
		GROUP BY
			TYPE,
			RATING
	) T
WHERE
	RANKING = 1;


-- 3. LIST ALL MOVIES RELEASED IN A SPECIFIC YEAR.. eg-2020

SELECT
	*
FROM
	NETFLIX
WHERE
	TYPE = 'Movie'
	AND RELEASE_YEAR = 2020;

-- 4. FIND THE TOP 5 CONTRIES WITH THE MOST CONTENT ON NETFLIX

SELECT
	TRIM(UNNEST(STRING_TO_ARRAY(COUNTRY, ','))) AS NEW_COUNTRY,
	COUNT(SHOW_ID) AS TOTAL_COUNT
FROM
	NETFLIX
WHERE
	COUNTRY IS NOT NULL
GROUP BY
	1
ORDER BY
	2 DESC
LIMIT
	5;

-- 5. IDENTIFY THE LONGEST MOVIE

SELECT
	*
FROM
	NETFLIX
WHERE
	TYPE = 'Movie'
	AND DURATION = (
		SELECT
			MAX(DURATION)
		FROM
			NETFLIX
	);

-- 6. FIND THE CONTENT ADDED IN THE LAST 5 YEARS

SELECT
	TYPE,
	DATE_ADDED,
	COUNT(*) AS TOTAL
FROM
	NETFLIX
WHERE
	DATE_ADDED IS NOT NULL
	AND TO_DATE(DATE_ADDED, 'Month DD, YYYY') >= CURRENT_DATE - INTERVAL '5 years'
GROUP BY
	TYPE,
	DATE_ADDED;

--7. FIND THE ALL THE MOVIES AND TV SHOWS DIRECTED BY THE RAJIV CHILAKA

SELECT
	*
FROM
	NETFLIX
WHERE
	DIRECTOR ILIKE '%Rajiv Chilaka%';

-- 8. LIST ALL TV SHOWS WITH MORE THAN 5 SEASONS
SELECT
	*
FROM
	NETFLIX
WHERE
	TYPE = 'TV Show'
	AND SPLIT_PART(DURATION, ' ', 1)::NUMERIC > 5;

-- 9. COUNT THE NUMBER OF CONTENT ITEM IN EACH GERNE

SELECT
	TRIM(UNNEST(STRING_TO_ARRAY(listed_in, ','))) AS GERNE,
	COUNT(SHOW_ID) AS TOTAL_COUNT
FROM
	NETFLIX
WHERE
	LISTED_IN IS NOT NULL
GROUP BY
	1;

-- 10. FIND EACH YEAR AND THE AVERAGE NUMBER OF CONTENT RELEASE BY INDIAON NETFLIX .
--		TOP 5 YEAR WITH HIGHEST AVG CONTENT RELEASE 

SELECT
	EXTRACT(YEAR FROM TO_DATE(date_added, 'Month DD ,YYYY')) AS year,
	COUNT(*) AS yearly_count,
	ROUND(COUNT(*)::NUMERIC/(SELECT COUNT(*) FROM netflix WHERE country = 'India')::numeric * 100,2) AS AVG_NO_OF_CONTENT_RELEASED
FROM netflix
WHERE country = 'India'
GROUP BY 1;


-- 11. LIST ALL THE MOVIES WHICH ARE DOCUMENTARIES 


SELECT
	TITLE,
	TYPE,
	GERNE
FROM
	(
		SELECT
			TITLE,
			TYPE,
			TRIM(UNNEST(STRING_TO_ARRAY(LISTED_IN, ','))) AS GERNE
		FROM
			NETFLIX
	) T
WHERE
	TYPE = 'Movie'
	AND GERNE = 'Documentaries';


-- 12. FIND ALL CONTENT WITHOUT A DIRECTOR

SELECT
	*
FROM
	NETFLIX
WHERE
	DIRECTOR IS NULL;


-- 13. FIND HOW MANY MOVIES ACTOR 'SALMAN KHAN' APPEARED IN LAST 10 YEARS

SELECT * FROM netflix
WHERE 
	casts LIKE '%Salman Khan%'
	AND 
	release_year > EXTRACT(YEAR FROM CURRENT_DATE)  - 10;


--14. FIND 10 ACTORS WHO HAVE APPEARED IN THE HIGHEST NUMBER OF MOVIES PRODUCED IN INDIA.

SELECT
	TRIM(UNNEST(STRING_TO_ARRAY(CASTS, ','))) AS ACTORS,
	COUNT(*) AS TOTAL_COUNT
FROM
	NETFLIX
WHERE
	TYPE = 'Movie'
	AND COUNTRY ILIKE '%India%'
GROUP BY
	1
ORDER BY
	2 DESC
LIMIT
	10;

--15. CATEGORIZED THE CONTENT BASED ON THE PRESENCE OF THE KEYWORDS 'KILL'  AND 'VIOLENCE ' IN THE DESCRIPTION FEILD.
-- LABEL CONTENT CONTAINNING THESE KEYWORDS AS 'BAD' AND ALL OTHER CONTENT AS 'GOOD', COUNT HOW MANY ITEMS FALL INTO EACH CATEGORY

WITH
	NEW_TABLE AS (
		SELECT
			*,
			CASE
				WHEN DESCRIPTION ILIKE '%Kill%'
				OR DESCRIPTION ILIKE '%Violence%' THEN 'BAD_CONTENT'
				ELSE 'GOOD_CONTENT'
			END CATEGORY
		FROM
			NETFLIX
	)
SELECT
	CATEGORY,
	COUNT(*) AS TOTAL_COUNT
FROM
	NEW_TABLE
GROUP BY
	1;









